name: Create zip archive on tag

on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: montudor/action-zip@v1.0.0

      - name: Create zip archive
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          zip -r temp.zip .
          mkdir Ivy_Payment
          unzip temp.zip -d Ivy_Payment
          rm temp.zip
          zip -r ivy_woo-${BRANCH_NAME}.zip Ivy_Payment
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Ivy_Payment
          path: Ivy_Payment

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ivy_woo-*.zip
